### ISSUE TITLE
모집중인프로젝트 API

### ISSUE THREAD

**Issue by sfsepark** [kyujonglee/yapp_backend#47]
1. 지역으로 프로젝트 검색
2. 각 키워드의 프로젝트가 몇 개 있는지 리턴
(ex : [1,4,5,6,3,1,2, ...])
3. 검색어로 검색
(요건 그냥 like query 날리면 되지않을까요? ㅜㅜ)

**Comment by sfsepark** [comment]
전체 관심키워드(= 추천 키워드) 에 대한 프로젝트 갯수

**Comment by kyujonglee** [comment]
- [ ] 각 키워드에 대한 프로젝트 count
